routes/web.php
<?php
use App\Mail\pruebaMail;
//INICIO
Route::get('/inicio', 'backendController@inicio');
//PANTALLA PRINCIPAL
Route::get('/', function () {
	return view('welcome');
});

Route::get('clave/{id}',function($clave){
	return bcrypt($clave);
});

Route::get('regular_pregunta','encuestaController@regular_pregunta');

// regist

//CERRAR SESION
Route::get('logout', 'LoginController@logout');
//INICIO DE SESION
Route::resource('login', 'LoginController');
Route::post('login', ['as' => 'login', 'uses' => 'LoginController@store']);
Route::post('loginx', ['as' => 'loginx', 'uses' => 'LoginController@login_profesional']);
// registo publico

	Route::get('registro', 'registroController@registro');
	Route::post('registro', 'registroController@registro_publico');


//PRUEBA DE EMAIL
Route::get('prueba_correo', function () {
    return Mail::to("stalin.molina96@hotmail.es", "Pruebas")->send(new pruebaMail());
});

//PARA REENVIAR CORREO DE CONFIRMACION
Route::get('recuperar-cuenta', 'usuarioController@recuperarcuenta');
//POST ENVIA CORREO PARA RECUPERAR CLAVE
Route::post('recuperar_clave', 'usuarioController@recuperar_clave');
//AL DAR CLICK EN EL MAIL DE RECUPERAR CLAVE
Route::get('recuperar-clave/{codigo}', 'LoginController@recuperarcontrasenia');
Route::post('enviar_clave', 'LoginController@enviar_clave');
Route::post('recuperar_clave', 'LoginController@recuperar_clave');
//AL DAR CLICK EN EL MAIL DE RECUPERAR CLAVE
Route::get('recuperar-clave/{codigo}', 'usuarioController@recuperarcontrasenia');
// AL INGRESAR NUEVA CONTRASEÑA (RECUPERAR CONTRASEÑA FORM)
Route::post('actualizar_clave_rec', 'usuarioController@actualizar_clave_rec');

// SUBIR FOTO
Route::post('subirfoto', ['as' => 'subirfoto', 'uses' => 'usuarioController@subirfoto']);
// ELIMINAR FOTO
Route::post('borrarfoto', ['as' => 'borrarfoto', 'uses' => 'usuarioController@borrarfoto']);

//SUBIR ENCUESTAS
Route::get('subir_encuestas', 'usuarioController@subir_encuestas');
Route::post('subir_encuesta_post', 'usuarioController@subir_encuesta_post');

//SUBIR PROFESIONALES
Route::get('subir_profesionales', 'usuarioController@subir_profesionales');
Route::post('subir_profesionales_post', 'usuarioController@subir_profesionales_post');

Route::get('subir_encargados', 'usuarioController@subir_encargados');
Route::post('subir_encargados_post', 'usuarioController@subir_encargados_post');









//RESPUESTA A ENCUESTAS
Route::get('responder_encuesta/{codigo}', 'encuestaController@responder_encuesta');
Route::post('responder_encuesta_post', 'encuestaController@responder_encuesta_post');

//RESULTADOS A ENCUESTAS
Route::get('resultados', 'encuestaController@vista_resultados');
Route::get('resultados/{id}', 'encuestaController@resultados');
Route::get('resultados_general/{id}', 'encuestaController@resultados_general');
Route::get('consultar_resultados_encuestas', 'encuestaController@consultar_resultados');
Route::get('obtener_pdf', 'encuestaController@obtener_pdf');


Route::delete('iniciar_sesion_user/{codigo}','usuarioController@iniciar_sesion_user');






Route::prefix('configuracion')->group(function () {
	//MENUS
	Route::resource('menus', 'menuController');
	//CARRERAS
	Route::resource('carreras', 'carreraController');
	//ROLES Y PERMISOS
	Route::resource('roles', 'rolController');
	//USUARIOS
	Route::resource('usuarios', 'usuarioController');
	//oute::post('registrarse', 'usuarioController@publico');






	//Route::post('registro', 'UsuarioController@registro_publico');
	//FACULTADES
	Route::resource('facultades', 'facultadController');
	//ENCUESTAS
	Route::resource('encuestas', 'encuestaController');
	//GESTIÓN DE PROFESIONALES
	Route::resource('profesionales', 'profesionalController');
	//CONFIGURACION DE ROLES Y PERMISOS
	Route::get('roles/administrar_permisos/{id}', 'rolController@administrar_permisos');
	//ciudades
	Route::resource('ciudades', 'ciudadController');
	//provincias
	Route::resource('provincias', 'provinciaController');
	//pais
	Route::resource('paises', 'paisController');
	//instituciones
	Route::resource('instituciones', 'institucionController');

	//tituloController
	Route::resource('titulos', 'tituloController');

	//configuracionController
	Route::resource('configuraciones','configuracionController');

	
});

	// GUARDAR PERMISOS DE ROLES
Route::post('guardar_permisos', 'rolController@guardar_permisos');


//AJAXS
Route::post('carrera_ajax', 'carreraController@carrera_ajax');
Route::post('usuarios/usuarios_ajax', 'usuarioController@usuarios_ajax');
Route::post('facultades/facultad_ajax', 'facultadController@facultad_ajax');
Route::get('profesional_ajax', 'profesionalController@profesional_ajax');
Route::post('ciudades_ajax', 'ciudadController@ciudades_ajax');
Route::post('provincias_ajax', 'provinciaController@provincias_ajax');
Route::post('paises/paises_ajax', 'paisController@paises_ajax');
Route::post('instituciones_ajax', 'institucionController@instituciones_ajax');

Route::post('titulos_ajax', 'tituloController@titulos_ajax');
Route::post('configuraciones_ajax', 'configuracionController@configuraciones_ajax');

//CONSULTAS

Route::get('consulta_usuario/{id}', 'LoginController@consulta_usuario');
Route::get('consultar_usuarios/{nombre}', 'usuarioController@consultar_usuarios');
Route::get('consultar_provincias/{nombre}', 'ubicacionController@consultar_provincias');
Route::get('consultar_ciudades/{nombre}', 'ubicacionController@consultar_ciudades');
Route::get('consultar_facultades/{nombre}', 'ubicacionController@consultar_facultades');
Route::get('consultar_carreras/{nombre}', 'ubicacionController@consultar_carreras');
Route::get('consultar_ciudad/{id}', 'ubicacionController@consultar_ciudad');
Route::get('consultar_provincia/{id}', 'ubicacionController@consultar_provincia');

Route::get('total_respuestas_ajax', 'encuestaController@total_respuestas_ajax');
Route::get('consultar_resultados_encuestas_cantidad', 'encuestaController@consultar_resultados_encuestas_cantidad');



Route::patch('actualizar_perfil/{id}','usuarioController@actualizar_perfil');
Route::patch('actualizar_clave/{id}','usuarioController@actualizar_clave');



//PERFIL DE USUARIO
Route::get('perfil',function(){
	if(Auth::user()->rol_id==3){
		return view('errors.403');
	}
	return view('perfil');
});


Route::patch('actualizar_preguntas/{id}','encuestaController@actualizar_preguntas');
Route::post('actualizar_pregunta','encuestaController@actualizar_pregunta');
Route::post('agregar_opcion','encuestaController@agregar_opcion');
Route::post('eliminar_dato_pregunta','encuestaController@eliminar_dato_pregunta');

resources/views/admin/roles/create.blade.php
<?php Autorizar(Request::path()); ?> 
@extends('layouts.master')
@section('header_styles')
<link href="{{ asset('assets/vendors/sweetalert2/css/sweetalert2.min.css')}}" rel="stylesheet">
    @endsection
@section('titulo','Crear rol')
@section('content')
    <div class="breadcrumb">
        <h1>
            Crear rol
        </h1>
    </div>
    <div class="separator-breadcrumb border-top">
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card mb-4">
                <div class="card-body">
                    <div class="card-title mb-3">
                        Nuevo rol
                    </div>
                    @include('alerts.errors')
                            @include('alerts.request')
                           {!! Form::open(['url'=>'configuracion/roles', 'method' => 'POST']) !!}
                    <div class="row">
                        <div class="col-md-6 form-group mb-3">
                            <label for="descripcion">
                                Descripción
                            </label>
                            {!! Form::Text('descripcion',null,['class'=>'form-control','placeholder'=>'Ingrese una descripción (Opcional)']) !!}
                        </div>
                        <div class="col-md-12">
                            <button class="btn btn-primary" type="submit">
                                Registrar
                            </button>
                        </div>
                    </div>
                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
    @endsection
@section('footer_scripts')
    <script src="{{ asset('assets/vendors/sweetalert2/js/sweetalert2.min.js')}}" type="text/javascript">
    </script>
    @endsection

resources/views/admin/roles/edit.blade.php
<?php Autorizar(Request::path()); ?> 
@extends('layouts.master')
@section('header_styles')

@endsection
@section('titulo','Editar rol')
@section('content')
<div class="breadcrumb">
    <h1>
        Editar rol
    </h1>
</div>
<div class="separator-breadcrumb border-top">
</div>
<div class="row">
    <div class="col-md-12">
        <div class="card mb-4">
            <div class="card-body">
                <div class="card-title mb-3">
                    Editar rol
                </div>
                @include('alerts.errors')
                            @include('alerts.request')
                             {!! Form::model($rol, array('method' => 'PATCH', 'url' => array('configuracion/roles', $rol->id))) !!}
                <div class="row">
                    <div class="col-md-6 form-group mb-3">
                        <label for="descripcion">
                            Descripción
                        </label>
                        {!! Form::Text('descripcion',null,['class'=>'form-control','placeholder'=>'Ingrese una descripción (Opcional)']) !!}
                    </div>
                    <div class="col-md-12">
                        <button class="btn btn-primary" type="submit">
                            Actualizar
                        </button>
                    </div>
                </div>
                {!! Form::close() !!}
            </div>
        </div>
    </div>
</div>
@endsection
@section('footer_scripts')
@endsection

resources/views/admin/roles/index.blade.php
<?php Autorizar(Request::path()); ?> 
@extends('layouts.master')
{{-- Page title --}}
@section('title')
    Roles del sistema @parent
@stop
{{-- page level styles --}}
@section('header_styles')
<!-- page vendors -->
<link href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
    <link href="{{ asset('assets/vendors/datatables/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
        <link href="{{ asset('assets/css/responsive.dataTables.css')}}" rel="stylesheet">
            <link href="{{ asset('assets/css/pages/datatables.css')}}" rel="stylesheet">
                <!--end of page vendors -->
                <link href="{{asset('assets/plugins/jquery-colorbox/example1/colorbox.css')}}" rel="stylesheet"/>
                <link href="{{asset('assets/plugins/jsTree/style.css')}}" rel="stylesheet">
                    <link href="{{ asset('assets/js/alertifyjs/css/alertify.min.css') }}" rel="stylesheet" type="text/css">
                        <link href="{{ asset('assets/js/alertifyjs/css/themes/alertify.core.css') }}" rel="stylesheet" type="text/css">
                            <script src="{{ asset('assets/js/alertifyjs/alertify.min.js') }}" type="text/javascript">
                            </script>
                            @stop
@section('content')
@include('alerts.errors')
@include('alerts.request')
@include('alerts.success')
                            <!-- Content Header (Page header) -->
                            <section class="content-header">
                                <h1>
                                    Roles del sistema
                                </h1>
                            </section>
                            <!-- Main content -->
                            <section class="content">
                                <div class="row">
                                    <div class="col-lg-12">
                                        <div class="card filterable">
                                            <div class="card-header clearfix">
                                                <h3 class="card-title pull-left m-t-6">
                                                    <i class="ti-control-shuffle">
                                                    </i>
                                                    Roles del sistema
                                                </h3>
                                                <div class="pull-right">
                                                    <a class="btn btn-primary btn-sm" href="{{ URL::route('roles.create') }}">
                                                        Nuevo
                                                    </a>
                                                </div>
                                            </div>
                                            <div class="card-body">
                                                <div class="table-responsive">
                                                    <table cellspacing="0" class="table" id="table" width="100%">
                                                        <thead>
                                                            <tr class="filters">
                                                                <th scope="col">
                                                                    ID
                                                                </th>
                                                                <!-- <th scope="col">ROL</th>-->
                                                                <th scope="col">
                                                                    DETALLE
                                                                </th>
                                                                <th scope="col">
                                                                    ACCIONES
                                                                </th>
                                                            </tr>
                                                        </thead>
                                                        <tbody>
                                                            @if (count($roles))
                                        @foreach ($roles as $rol)
                                                            <tr id="tr{{ $rol->id }}">
                                                                <td>
                                                                    {{ $rol->id }}
                                                                </td>
                                                                <!--<td>{{ $rol->nombre }}</td>-->
                                                                <td>
                                                                    {{ $rol->descripcion }}
                                                                </td>
                                                                <td>
                                                                    <a class="btn btn-sm btn-default" data-placement="top" data-toggle="tooltip" href="{{ route('roles.edit',$rol->id) }}" title="Editar Rol">
                                                                        <i class="fa fa-edit">
                                                                        </i>
                                                                    </a>
                                                                    <a class="btn btn-sm btn-default js-sweetalert" onclick="SeguroEliminar({{$rol->id}})" title="Eliminar Rol">
                                                                        <i class="fa fa-trash-o text-danger">
                                                                        </i>
                                                                        <a class="btn btn-sm btn-default js-sweetalert" data-placement="top" data-toggle="tooltip" onclick="administrar_permisos({{$rol->id}})" title="Configurar permisos">
                                                                            <i class="fa fa-key">
                                                                            </i>
                                                                        </a>
                                                                    </a>
                                                                </td>
                                                            </tr>
                                                            @endforeach
                                                        </tbody>
                                                    </table>
                                                    @endif
                                                </div>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!-- fourth datatable end -->
                                <!-- fifth row datatable -->
                                <!-- fifth row datatable end -->
                            </section>
                            <!-- /.content -->
                            @stop
@section('footer_scripts')
                            <!--   page level js -->
                            <script src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js')}}" type="text/javascript">
                            </script>
                            <script src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap4.js')}}" type="text/javascript">
                            </script>
                            <script src="{{ asset('assets/vendors/datatables/js/dataTables.buttons.min.js')}}" type="text/javascript">
                            </script>
                            <script src="{{ asset('assets/vendors/datatables/js/buttons.print.min.js')}}" type="text/javascript">
                            </script>
                            <script src="{{ asset('assets/vendors/datatables/js/buttons.html5.min.js')}}" type="text/javascript">
                            </script>
                            <script src="{{ asset('assets/vendors/datatables/js/buttons.bootstrap4.min.js')}}" type="text/javascript">
                            </script>
                            <script src="{{ asset('assets/vendors/datatables/js/dataTables.responsive.js')}}" type="text/javascript">
                            </script>
                            <script src="{{ asset('assets/js/pages/advanced_tables.js')}}" type="text/javascript">
                            </script>
                            <!-- end of page level js -->
                            <script src="{{asset('assets/plugins/jquery-colorbox/jquery.colorbox.js')}}" type="text/javascript">
                            </script>
                            <script src="{{asset('assets/plugins/jsTree/jstree.min.js')}}">
                            </script>
                            <script type="text/javascript">



    'use strict';
  var table = $('#table').DataTable({
   responsive: true,
    language: {
        "decimal": "",
        "emptyTable": "No hay información",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ Entradas",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
        }
    },
  
});
 



    $(document).ready(function(){
        $(".dataTables_length .form-control").removeClass('form-control-sm');
    })

    function administrar_permisos(id){
        var direccion="{{ url('configuracion/roles/administrar_permisos') }}/"+id;
        $.colorbox({href : direccion, width:"100%", height:"100%"});
    }

      function SeguroEliminar($id)
    {
      alertify.confirm('Confirmar', '¿Desea eliminar este usuario?', 
        function()
        {
            $.ajax({
               url: "{{ url(request()->route()->getPrefix().'/roles') }}/"+$id,
               data: { "_token": "{{ csrf_token() }}" },
              type: 'DELETE',
            })
            .done(function() {
              location.reload();
              desaparecer_carga_ajax();
            })
             .fail(function() {
              desaparecer_carga_ajax();
            })
             .always(function() {
              desaparecer_carga_ajax();
            });
              },
          function(){});


        }
                            </script>
                            @stop

resources/views/admin/roles/permisos.blade.php
<script>
$(document).ready(function () {
    $('#jstree').on('changed.jstree', function (e, data) {
        var i, j, r = [];
        for(i = 0, j = data.selected.length; i < j; i++) {
            r.push(data.instance.get_node(data.selected[i]).text);
            //r.push(data.instance.get_node(data.selected[i]).text.)
        }
        //$('#event_result').html('Selected: ' + r.join(', '));
        var valor = r.join(', ');
        valor= valor.replace(/idmenu/g,'idmenumain[]');
        //valor= valor.replace(/hidden/g,'text');
        $('#divselect').html(valor);
        //            alert (valor);
    }).jstree({
        'state': {
            'opened': true
            },
        'core' : {
            'check_callback' : true
        },
        "checkbox" : {
            "keep_selected_style" : false
        },
        "plugins" : [ "checkbox" ]                                      
    }) ;             
});
</script>
<div class="breadcrumb">
    <center>
        <h1>
            Permisos para el rol
            <strong>
                {{ $rol->descripcion }}
            </strong>
        </h1>
    </center>
</div>
<div class="separator-breadcrumb border-top">
</div>
<div class="card mb-8">
    {!! Form::open(['url'=>'guardar_permisos', 'method' => 'POST']) !!}
    <input name="rol_id" type="hidden" value="{{ $rol->id }}">
        <div class="card-body">
            <div class="row">
                <div class="col-md-12 form-group mb-3" id="jstree">
                    <ul>
                        <li class="jstree-open">
                            Todos los Menus
                            <ul>
                                <?php
                                $rol_id=$rol->
                                id;
                                $menuselec="";
                                $idmesel=0;
                                $menu= $tabla;
                                ?>
                                @foreach ($tabla as $tab)
                                <?php 
                                        $versela=App\AsignarPermisosModel::where('idmenu',$tab->id)
                                        ->where('idrol',$rol_id)->first(); 
                                        ?>
                               
                                       
                                        
                                         @if(!count($tab->menus))
                                                @if($versela)
                                                <li class='jstree-open' data-jstree='{"selected":true}'>
                                                <input type="hidden" name="idmenu{{ $tab->id }}" value="{{ $tab->id }}"> {{ $tab->menu }}  
                                                @else
                                                <li class="jstree-open">
                                                <input name="idmenu{{ $tab->id }}" type="hidden" value="{{ $tab->id }}">
                                                {{ $tab->menu }} 
                                                @endif                                   
                                        @else 
                                        <li class='jstree-open'>
                                            <input type="hidden" name="idmenu{{ $tab->id }}" value="{{ $tab->id }}"> {{ $tab->menu }} 
                                        <ul>
                                            @foreach($tab->menus as $menux)
                                            <?php
                                        $verselx=App\AsignarPermisosModel::where('idmenu',$menux->
                                            id)
                                        ->where('idrol',$rol_id)->first();                              
                                        ?>
                                        @if($verselx)
                                            <li class="jstree-open" data-jstree='{"selected":true}'>
                                                <input name="idmenu{{ $menux->id }}" type="hidden" value="{{ $menux->id }}">
                                                    {{ $menux->menu }}
                                                </input>
                                            </li>
                                            @else
                                            <li class="jstree-open">
                                                <input name="idmenu{{ $menux->id }}" type="hidden" value="{{ $menux->id }}">
                                                    {{ $menux->menu }}
                                                </input>
                                            </li>
                                            @endif
                                        @endforeach
                                    </li>
                                        </ul>
                                        @endif
                                    </input>
                                </li>
                                @endforeach
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="car-footer">
            <div class="col-md-12 form-group mb-3">
                <center>
                    <button class="btn btn-primary" type="submit">
                       <i class="fa fa-save">  </i> Guardar Permisos
                    </button>
                </center>
            </div>
        </div>
        <div id="divselect" style="display:none">
            {!! Form::close() !!}
        </div>
    </input>
</div>