routes/web.php
<?php
use App\Mail\pruebaMail;
//INICIO
Route::get('/inicio', 'backendController@inicio');
//PANTALLA PRINCIPAL
Route::get('/', function () {
	return view('welcome');
});

Route::get('clave/{id}',function($clave){
	return bcrypt($clave);
});

Route::get('regular_pregunta','encuestaController@regular_pregunta');

// regist

//CERRAR SESION
Route::get('logout', 'LoginController@logout');
//INICIO DE SESION
Route::resource('login', 'LoginController');
Route::post('login', ['as' => 'login', 'uses' => 'LoginController@store']);
Route::post('loginx', ['as' => 'loginx', 'uses' => 'LoginController@login_profesional']);
// registo publico

	Route::get('registro', 'registroController@registro');
	Route::post('registro', 'registroController@registro_publico');


//PRUEBA DE EMAIL
Route::get('prueba_correo', function () {
    return Mail::to("stalin.molina96@hotmail.es", "Pruebas")->send(new pruebaMail());
});

//PARA REENVIAR CORREO DE CONFIRMACION
Route::get('recuperar-cuenta', 'usuarioController@recuperarcuenta');
//POST ENVIA CORREO PARA RECUPERAR CLAVE
Route::post('recuperar_clave', 'usuarioController@recuperar_clave');
//AL DAR CLICK EN EL MAIL DE RECUPERAR CLAVE
Route::get('recuperar-clave/{codigo}', 'LoginController@recuperarcontrasenia');
Route::post('enviar_clave', 'LoginController@enviar_clave');
Route::post('recuperar_clave', 'LoginController@recuperar_clave');
//AL DAR CLICK EN EL MAIL DE RECUPERAR CLAVE
Route::get('recuperar-clave/{codigo}', 'usuarioController@recuperarcontrasenia');
// AL INGRESAR NUEVA CONTRASEÑA (RECUPERAR CONTRASEÑA FORM)
Route::post('actualizar_clave_rec', 'usuarioController@actualizar_clave_rec');

// SUBIR FOTO
Route::post('subirfoto', ['as' => 'subirfoto', 'uses' => 'usuarioController@subirfoto']);
// ELIMINAR FOTO
Route::post('borrarfoto', ['as' => 'borrarfoto', 'uses' => 'usuarioController@borrarfoto']);

//SUBIR ENCUESTAS
Route::get('subir_encuestas', 'usuarioController@subir_encuestas');
Route::post('subir_encuesta_post', 'usuarioController@subir_encuesta_post');

//SUBIR PROFESIONALES
Route::get('subir_profesionales', 'usuarioController@subir_profesionales');
Route::post('subir_profesionales_post', 'usuarioController@subir_profesionales_post');

Route::get('subir_encargados', 'usuarioController@subir_encargados');
Route::post('subir_encargados_post', 'usuarioController@subir_encargados_post');









//RESPUESTA A ENCUESTAS
Route::get('responder_encuesta/{codigo}', 'encuestaController@responder_encuesta');
Route::post('responder_encuesta_post', 'encuestaController@responder_encuesta_post');

//RESULTADOS A ENCUESTAS
Route::get('resultados', 'encuestaController@vista_resultados');
Route::get('resultados/{id}', 'encuestaController@resultados');
Route::get('resultados_general/{id}', 'encuestaController@resultados_general');
Route::get('consultar_resultados_encuestas', 'encuestaController@consultar_resultados');
Route::get('obtener_pdf', 'encuestaController@obtener_pdf');


Route::delete('iniciar_sesion_user/{codigo}','usuarioController@iniciar_sesion_user');






Route::prefix('configuracion')->group(function () {
	//MENUS
	Route::resource('menus', 'menuController');
	//CARRERAS
	Route::resource('carreras', 'carreraController');
	//ROLES Y PERMISOS
	Route::resource('roles', 'rolController');
	//USUARIOS
	Route::resource('usuarios', 'usuarioController');
	//oute::post('registrarse', 'usuarioController@publico');






	//Route::post('registro', 'UsuarioController@registro_publico');
	//FACULTADES
	Route::resource('facultades', 'facultadController');
	//ENCUESTAS
	Route::resource('encuestas', 'encuestaController');
	//GESTIÓN DE PROFESIONALES
	Route::resource('profesionales', 'profesionalController');
	//CONFIGURACION DE ROLES Y PERMISOS
	Route::get('roles/administrar_permisos/{id}', 'rolController@administrar_permisos');
	//ciudades
	Route::resource('ciudades', 'ciudadController');
	//provincias
	Route::resource('provincias', 'provinciaController');
	//pais
	Route::resource('paises', 'paisController');
	//instituciones
	Route::resource('instituciones', 'institucionController');

	//tituloController
	Route::resource('titulos', 'tituloController');

	//configuracionController
	Route::resource('configuraciones','configuracionController');

	
});

	// GUARDAR PERMISOS DE ROLES
Route::post('guardar_permisos', 'rolController@guardar_permisos');


//AJAXS
Route::post('carrera_ajax', 'carreraController@carrera_ajax');
Route::post('usuarios/usuarios_ajax', 'usuarioController@usuarios_ajax');
Route::post('facultades/facultad_ajax', 'facultadController@facultad_ajax');
Route::get('profesional_ajax', 'profesionalController@profesional_ajax');
Route::post('ciudades_ajax', 'ciudadController@ciudades_ajax');
Route::post('provincias_ajax', 'provinciaController@provincias_ajax');
Route::post('paises/paises_ajax', 'paisController@paises_ajax');
Route::post('instituciones_ajax', 'institucionController@instituciones_ajax');

Route::post('titulos_ajax', 'tituloController@titulos_ajax');
Route::post('configuraciones_ajax', 'configuracionController@configuraciones_ajax');

//CONSULTAS

Route::get('consulta_usuario/{id}', 'LoginController@consulta_usuario');
Route::get('consultar_usuarios/{nombre}', 'usuarioController@consultar_usuarios');
Route::get('consultar_provincias/{nombre}', 'ubicacionController@consultar_provincias');
Route::get('consultar_ciudades/{nombre}', 'ubicacionController@consultar_ciudades');
Route::get('consultar_facultades/{nombre}', 'ubicacionController@consultar_facultades');
Route::get('consultar_carreras/{nombre}', 'ubicacionController@consultar_carreras');
Route::get('consultar_ciudad/{id}', 'ubicacionController@consultar_ciudad');
Route::get('consultar_provincia/{id}', 'ubicacionController@consultar_provincia');

Route::get('total_respuestas_ajax', 'encuestaController@total_respuestas_ajax');
Route::get('consultar_resultados_encuestas_cantidad', 'encuestaController@consultar_resultados_encuestas_cantidad');



Route::patch('actualizar_perfil/{id}','usuarioController@actualizar_perfil');
Route::patch('actualizar_clave/{id}','usuarioController@actualizar_clave');



//PERFIL DE USUARIO
Route::get('perfil',function(){
	if(Auth::user()->rol_id==3){
		return view('errors.403');
	}
	return view('perfil');
});


Route::patch('actualizar_preguntas/{id}','encuestaController@actualizar_preguntas');
Route::post('actualizar_pregunta','encuestaController@actualizar_pregunta');
Route::post('agregar_opcion','encuestaController@agregar_opcion');
Route::post('eliminar_dato_pregunta','encuestaController@eliminar_dato_pregunta');

resources/views/admin/ciudades/crear.blade.php
<?php Autorizar(Request::path()); ?> 

@extends('layouts.master')
@section('header_styles')        
<link rel="stylesheet" href="{{ asset('assets/vendors/select2/css/select2.min.css')}}">
@endsection

@section('title')
    Crear ciudad @parent
@stop
@section('content')
@include('alerts.errors')
@include('alerts.request')
@include('alerts.success')
        <div class="breadcrumb">
            <h1>
                Crear ciudad
            </h1>
        </div>
        <div class="separator-breadcrumb border-top">
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="card-title mb-3">
                            Nuevo ciudad
                        </div>
                        @include('alerts.errors')
                            @include('alerts.request')
                           {!! Form::open(['route'=>'ciudades.store', 'method' => 'POST']) !!}
                        <div class="row">
                            
                         
                            <div class="col-md-6 form-group mb-3">
                                <label for="nombre">
                                    Nombre
                                </label>
                                {!! Form::Text('nombre',null,['class'=>'form-control','placeholder'=>'Ingrese el nombre']) !!}
                            </div>
                                   
                            <div class="col-md-6 form-group mb-3">
                                <label for="provincia_id">
                                    Provincia
                                </label>
                                {!! Form::select('provincia_id',$provincia,null,['class'=>'form-control select2']) !!}
                            </div>
                          
                     
                            <div class="col-md-12">
                                <button class="btn btn-primary" type="submit">
                                    Registrar
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
        @endsection
@section('footer_scripts')
    <script src="{{ asset('assets/vendors/select2/js/select2.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function()  {
          $(".select2").select2({width: "100%"});
        });
    </script>


        @endsection
 

resources/views/admin/ciudades/edit.blade.php
<?php Autorizar(Request::path()); ?> 
@extends('layouts.master')
@section('header_styles')
<!-- page vendors -->
    <link href="{{asset('assets/vendors/select2/css/select2.min.css')}}" rel="stylesheet" type="text/css">
                            @endsection
@section('title')
    Editar ciudad @parent
@stop
@section('content')
                            <section class="content-header">
                                <h1>
                                    Editar ciudad
                                </h1>
                            </section>
                            <section class="content">
                                <div class="row">
                                    <div class="col-md-12">
                                        <div class="card">
                                            <div class="card-header">
                                                <h3 class="card-title">
                                                    Editar ciudad
                                                </h3>
                                            </div>
                                            <div class="card-body">
                                                @include('alerts.errors')
                            @include('alerts.request')
                            {!! Form::model($ciudad, array('method' => 'PATCH', 'route' => array('ciudades.update', $ciudad->id))) !!}
                                                <div class="row">
                                                    <div class="col-md-6 form-group mb-3">
                                                        <label for="nombre">
                                                            Nombre
                                                        </label>
                                                        {!! Form::Text('nombre',null,['class'=>'form-control']) !!}
                                                    </div>
                                                    <div class="col-md-6 form-group mb-3">
                                                        <label for="provincia_id">
                                                            Provincia
                                                        </label><!--
                                                        <select class="search-field" id="select_pais" name="pais_id">
                                                        </select>-->
                                                         {!! Form::select('provincia_id',$provincia,null,['class'=>'form-control select2']) !!}
                                                    </div>
                                                    <div class="col-md-12">
                                                        <button class="btn btn-primary" type="submit">
                                                            Actualizar
                                                        </button>
                                                    </div>
                                                </div>
                                            
                                                {!! Form::close() !!}
                                            </div>
                                        </div>
                                    </div>
                                </div>
                                <!--row end-->
                            </section>
                            @endsection
@section('footer_scripts')
                        <script src="{{ asset('assets/vendors/select2/js/select2.js')}}" type="text/javascript"></script>
    <script type="text/javascript">
        $(document).ready(function()  {
          $(".select2").select2({width: "100%"});
        });
    </script>
                           
                            @endsection

resources/views/admin/ciudades/index.blade.php
<?php Autorizar(Request::path()); ?> 
@extends('layouts.master')
{{-- Page title --}}
@section('title')
    Ciudades @parent
@stop
{{-- page level styles --}}
@section('header_styles')
<!-- page vendors -->
<link href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
    <link href="{{ asset('assets/vendors/datatables/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
        <link href="{{ asset('assets/css/responsive.dataTables.css')}}" rel="stylesheet">
            <link href="{{ asset('assets/css/pages/datatables.css')}}" rel="stylesheet">
                <link href="{{ asset('assets/js/alertifyjs/css/alertify.min.css') }}" rel="stylesheet" type="text/css">
                    <link href="{{ asset('assets/js/alertifyjs/css/themes/alertify.core.css') }}" rel="stylesheet" type="text/css">
                        <script src="{{ asset('assets/js/alertifyjs/alertify.min.js') }}" type="text/javascript">
                        </script>
                        <!--end of page vendors -->
                        @stop
@section('content')
@include('alerts.errors')
@include('alerts.request')
@include('alerts.success')
                        <!-- Content Header (Page header) -->
                        <section class="content-header">
                            <h1>
                                Gestión de Ciudades
                            </h1>
                        </section>
                        <!-- Main content -->
                        <section class="content">
                            <div class="row">
                                <div class="col-lg-12">
                                    <div class="card filterable">
                                        <div class="card-header clearfix">
                                            <h3 class="card-title pull-left m-t-6">
                                                <i class="ti-control-shuffle">
                                                </i>
                                                Ciudades
                                                <!--Add / Remove rows-->
                                            </h3>
                                            <div class="pull-right">
                                                <a class="btn btn-primary btn-sm" href="{{ URL::route('ciudades.create') }}" type="button">
                                                    Nuevo
                                                </a>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <div class="table-responsive">
                                                <table cellspacing="0" class="table" id="tabla" width="100%">
                                                    <thead>
                                                        <tr>
                                                            <th>
                                                                Id
                                                            </th>
                                                            <th>
                                                               Nombre
                                                            </th>
                                                            <th>
                                                                Provincia
                                                            </th>
                                                            <th width="10%">
                                                                Opciones
                                                            </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                    </tbody>
                                                </table>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            <!-- fourth datatable end -->
                            <!-- fifth row datatable -->
                            <!-- fifth row datatable end -->
                        </section>
                        <!-- /.content -->
                        @stop
@section('footer_scripts')
                        <!--   page level js -->
                        <script src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js')}}" type="text/javascript">
                        </script>
                        <script src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap4.js')}}" type="text/javascript">
                        </script>
                        <script src="{{ asset('assets/vendors/datatables/js/dataTables.buttons.min.js')}}" type="text/javascript">
                        </script>
                        <script src="{{ asset('assets/vendors/datatables/js/buttons.print.min.js')}}" type="text/javascript">
                        </script>
                        <script src="{{ asset('assets/vendors/datatables/js/buttons.html5.min.js')}}" type="text/javascript">
                        </script>
                        <script src="{{ asset('assets/vendors/datatables/js/buttons.bootstrap4.min.js')}}" type="text/javascript">
                        </script>
                        <script src="{{ asset('assets/vendors/datatables/js/dataTables.responsive.js')}}" type="text/javascript">
                        </script>
                        <script src="{{ asset('assets/js/pages/advanced_tables.js')}}" type="text/javascript">
                        </script>
                        <!-- end of page level js -->
                        <script>
                            /*
    $(function () {
         $("[rel='tooltip']").tooltip();
    })
    function SeguroEliminar(id)
   {
    $.colorbox({width:"auto",height:"auto", open:true, href:"seguro_eliminar/carreraarticulos/"+id});
   }
*/


     var table=null;
    $(document).ready(function () {
        table=$('#tabla').DataTable({
                //responsive : true,
                "lengthMenu": [[10, 25, 50, -1], [10, 25, 50, "All"]],
                language: {
                    "emptyTable":     "No hay provincias  aún",
                    "info":           "Mostrando _START_ a _END_ de _TOTAL_ provincias",
                    "infoEmpty":      "Mostrando 0 a 0 de 0 provincias",
                    "infoFiltered":   "(filtered from _MAX_ total entries)",
                    "infoPostFix":    "",
                    "thousands":      ",",
                    "lengthMenu":     "Mostrar _MENU_ entradas",
                    "loadingRecords": "Cargando...",
                    "processing":     "Procesando...",
                    "search":         "Buscar:",
                    "zeroRecords":    "No se encontraron registros coincidentes",
                    "paginate": {
                        "first":      "Primero",
                        "last":       "Último",
                        "next":       "Siguiente",
                        "previous":   "Atrás"
                    },
                    "aria": {
                        "sortAscending":  ": activate to sort column ascending",
                        "sortDescending": ": activate to sort column descending"
                    }
                },
              
                    "order": ([ 0, 'desc' ]),
        dom: 'flrBtip',//Bflipt
        buttons: [
            'print','copy', 'excel', 'pdf'
        ],
        "processing": true,
            "serverSide": true,
            "ajax":{
                     "url": "{{ url('ciudades_ajax') }}",
                     "dataType": "json",
                     "type": "POST",
                     "data":{ _token: "{{csrf_token()}}"}
                   },
            "columns": [
                { "data": "id" },
                { "data": "ciudad" },                
                { "data": "provincia" },  
                { "data": "acciones","orderable":false }
                ]                             
            });  
    });
        

  function SeguroEliminar($id)
    {
      alertify.confirm('Confirma', '¿Desea eliminar esta provincias?', 

        function()
        {

            $.ajax({
               url: "{{ url(request()->route()->getPrefix().'/ciudades') }}/"+$id,
               data: { "_token": "{{ csrf_token() }}" },
              type: 'DELETE',
            })
            .done(function() {
              location.reload();
              desaparecer_carga_ajax();
            })
             .fail(function() {
              desaparecer_carga_ajax();
            })
             .always(function() {
              desaparecer_carga_ajax();
            });
              },
          function(){});


        }
                        </script>
                        @stop
   