routes/web.php
<?php
use App\Mail\pruebaMail;
//INICIO
Route::get('/inicio', 'backendController@inicio');
//PANTALLA PRINCIPAL
Route::get('/', function () {
	return view('welcome');
});

Route::get('clave/{id}',function($clave){
	return bcrypt($clave);
});

Route::get('regular_pregunta','encuestaController@regular_pregunta');

// regist

//CERRAR SESION
Route::get('logout', 'LoginController@logout');
//INICIO DE SESION
Route::resource('login', 'LoginController');
Route::post('login', ['as' => 'login', 'uses' => 'LoginController@store']);
Route::post('loginx', ['as' => 'loginx', 'uses' => 'LoginController@login_profesional']);
// registo publico

	Route::get('registro', 'registroController@registro');
	Route::post('registro', 'registroController@registro_publico');


//PRUEBA DE EMAIL
Route::get('prueba_correo', function () {
    return Mail::to("stalin.molina96@hotmail.es", "Pruebas")->send(new pruebaMail());
});

//PARA REENVIAR CORREO DE CONFIRMACION
Route::get('recuperar-cuenta', 'usuarioController@recuperarcuenta');
//POST ENVIA CORREO PARA RECUPERAR CLAVE
Route::post('recuperar_clave', 'usuarioController@recuperar_clave');
//AL DAR CLICK EN EL MAIL DE RECUPERAR CLAVE
Route::get('recuperar-clave/{codigo}', 'LoginController@recuperarcontrasenia');
Route::post('enviar_clave', 'LoginController@enviar_clave');
Route::post('recuperar_clave', 'LoginController@recuperar_clave');
//AL DAR CLICK EN EL MAIL DE RECUPERAR CLAVE
Route::get('recuperar-clave/{codigo}', 'usuarioController@recuperarcontrasenia');
// AL INGRESAR NUEVA CONTRASEÑA (RECUPERAR CONTRASEÑA FORM)
Route::post('actualizar_clave_rec', 'usuarioController@actualizar_clave_rec');

// SUBIR FOTO
Route::post('subirfoto', ['as' => 'subirfoto', 'uses' => 'usuarioController@subirfoto']);
// ELIMINAR FOTO
Route::post('borrarfoto', ['as' => 'borrarfoto', 'uses' => 'usuarioController@borrarfoto']);

//SUBIR ENCUESTAS
Route::get('subir_encuestas', 'usuarioController@subir_encuestas');
Route::post('subir_encuesta_post', 'usuarioController@subir_encuesta_post');

//SUBIR PROFESIONALES
Route::get('subir_profesionales', 'usuarioController@subir_profesionales');
Route::post('subir_profesionales_post', 'usuarioController@subir_profesionales_post');

Route::get('subir_encargados', 'usuarioController@subir_encargados');
Route::post('subir_encargados_post', 'usuarioController@subir_encargados_post');









//RESPUESTA A ENCUESTAS
Route::get('responder_encuesta/{codigo}', 'encuestaController@responder_encuesta');
Route::post('responder_encuesta_post', 'encuestaController@responder_encuesta_post');

//RESULTADOS A ENCUESTAS
Route::get('resultados', 'encuestaController@vista_resultados');
Route::get('resultados/{id}', 'encuestaController@resultados');
Route::get('resultados_general/{id}', 'encuestaController@resultados_general');
Route::get('consultar_resultados_encuestas', 'encuestaController@consultar_resultados');
Route::get('obtener_pdf', 'encuestaController@obtener_pdf');


Route::delete('iniciar_sesion_user/{codigo}','usuarioController@iniciar_sesion_user');






Route::prefix('configuracion')->group(function () {
	//MENUS
	Route::resource('menus', 'menuController');
	//CARRERAS
	Route::resource('carreras', 'carreraController');
	//ROLES Y PERMISOS
	Route::resource('roles', 'rolController');
	//USUARIOS
	Route::resource('usuarios', 'usuarioController');
	//oute::post('registrarse', 'usuarioController@publico');






	//Route::post('registro', 'UsuarioController@registro_publico');
	//FACULTADES
	Route::resource('facultades', 'facultadController');
	//ENCUESTAS
	Route::resource('encuestas', 'encuestaController');
	//GESTIÓN DE PROFESIONALES
	Route::resource('profesionales', 'profesionalController');
	//CONFIGURACION DE ROLES Y PERMISOS
	Route::get('roles/administrar_permisos/{id}', 'rolController@administrar_permisos');
	//ciudades
	Route::resource('ciudades', 'ciudadController');
	//provincias
	Route::resource('provincias', 'provinciaController');
	//pais
	Route::resource('paises', 'paisController');
	//instituciones
	Route::resource('instituciones', 'institucionController');

	//tituloController
	Route::resource('titulos', 'tituloController');

	//configuracionController
	Route::resource('configuraciones','configuracionController');

	
});

	// GUARDAR PERMISOS DE ROLES
Route::post('guardar_permisos', 'rolController@guardar_permisos');


//AJAXS
Route::post('carrera_ajax', 'carreraController@carrera_ajax');
Route::post('usuarios/usuarios_ajax', 'usuarioController@usuarios_ajax');
Route::post('facultades/facultad_ajax', 'facultadController@facultad_ajax');
Route::get('profesional_ajax', 'profesionalController@profesional_ajax');
Route::post('ciudades_ajax', 'ciudadController@ciudades_ajax');
Route::post('provincias_ajax', 'provinciaController@provincias_ajax');
Route::post('paises/paises_ajax', 'paisController@paises_ajax');
Route::post('instituciones_ajax', 'institucionController@instituciones_ajax');

Route::post('titulos_ajax', 'tituloController@titulos_ajax');
Route::post('configuraciones_ajax', 'configuracionController@configuraciones_ajax');

//CONSULTAS

Route::get('consulta_usuario/{id}', 'LoginController@consulta_usuario');
Route::get('consultar_usuarios/{nombre}', 'usuarioController@consultar_usuarios');
Route::get('consultar_provincias/{nombre}', 'ubicacionController@consultar_provincias');
Route::get('consultar_ciudades/{nombre}', 'ubicacionController@consultar_ciudades');
Route::get('consultar_facultades/{nombre}', 'ubicacionController@consultar_facultades');
Route::get('consultar_carreras/{nombre}', 'ubicacionController@consultar_carreras');
Route::get('consultar_ciudad/{id}', 'ubicacionController@consultar_ciudad');
Route::get('consultar_provincia/{id}', 'ubicacionController@consultar_provincia');

Route::get('total_respuestas_ajax', 'encuestaController@total_respuestas_ajax');
Route::get('consultar_resultados_encuestas_cantidad', 'encuestaController@consultar_resultados_encuestas_cantidad');



Route::patch('actualizar_perfil/{id}','usuarioController@actualizar_perfil');
Route::patch('actualizar_clave/{id}','usuarioController@actualizar_clave');



//PERFIL DE USUARIO
Route::get('perfil',function(){
	if(Auth::user()->rol_id==3){
		return view('errors.403');
	}
	return view('perfil');
});


Route::patch('actualizar_preguntas/{id}','encuestaController@actualizar_preguntas');
Route::post('actualizar_pregunta','encuestaController@actualizar_pregunta');
Route::post('agregar_opcion','encuestaController@agregar_opcion');
Route::post('eliminar_dato_pregunta','encuestaController@eliminar_dato_pregunta');

app/Http/Controllers/encuestaController.php
<?php

namespace App\Http\Controllers;

use App\encuestaModel;
use App\usuarioModel;
use App\direccion_carreraModel;
use App\carreraModel;
use App\opcionModel;
use App\preguntaModel;
use App\respuestaModel;
use App\respuesta_encuestaModel;
use App\grupopreguntasModel;
use Auth;
use DB;
use Illuminate\Http\Request;
use Redirect;
use Session;
use Barryvdh\DomPDF\Facade as PDF;

class encuestaController extends Controller
{
    public function vista_resultados()
    {
        $encuestas = encuestaModel::all();
        return view('resultados.index', compact('encuestas'));
    }
    public function index()
    {
        $encuestas = encuestaModel::all();
        return view('admin.encuestas.index', compact('encuestas'));
    }
    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

        function consultar_resultados_encuestas_cantidad(){
        $request=request();
        $where_carrera='0=0';
        $where_periodo="'0'='0'";
        $where_anios='0=0';

        
        if(Auth::user()->rol_id!=1&&Auth::user()->rol_id!=5){
            $where_carrera='0=1';
        }
        

        if($request->carreras){
            $dat='';
            foreach ($request->carreras as $key => $value) {
                $dat.=$value.',';
            }
            $dat = trim($dat, ",");
            $where_carrera="usuario.carrera_id IN ($dat)";
        }

         if($request->periodos){
            $datx='';
            foreach ($request->periodos as $key => $periodo) {
                $datx.="'$periodo',";
            }
            $datx = trim($datx, ",");
            $where_periodo="usuario.periodo_academico IN ($datx)";
        }

         if($request->anios){
            $anios='';
            foreach ($request->anios as $key => $an) {
                $anios.=intval($an).',';
            }
            $anios = trim($anios, ",");
            $where_anios="usuario.anio_graduacion IN ($anios)";
        }

        $total_profesionales=usuarioModel::whereraw($where_carrera)
        ->whereraw($where_anios)
        ->whereraw($where_periodo)
        ->where('rol_id',3)
        ->count();


        $total_profesionales_respondidos=respuesta_encuestaModel::join('usuario','usuario.id','respuesta_encuesta.usuario_id')
        ->where('encuesta_id',$request->id)
        ->whereraw($where_carrera)
        ->whereraw($where_anios)
        ->whereraw($where_periodo)
        ->count();

        $sin_respuesta=$total_profesionales-$total_profesionales_respondidos;

        return response()->json(array('Total' => $total_profesionales, 'que han respondido' => $total_profesionales_respondidos, 'que no han respondido' => $sin_respuesta));              
    }

    public function total_respuestas_ajax()
    {
        $request=request();
        $tipo_respuesta=$request->tipo_respuestas;
        $where_carrera='0=0';
        $where_periodo="'0'='0'";
        $where_anios='0=0';
        $where_respuesta='0=0';
        $encuesta_id=$request->id;

        if($tipo_respuesta!=''&&$tipo_respuesta!=null){
            if($tipo_respuesta=='SI'){
                $where_respuesta='respuesta_encuesta.encuesta_id is not null';
            }
            if($tipo_respuesta=='NO'){
                $where_respuesta='respuesta_encuesta.encuesta_id is null';
            }

        }
        
        if(Auth::user()->rol_id!=1&&Auth::user()->rol_id!=5){
            $where_carrera='0=1';
        }
        

        if($request->carreras){
            $dat='';
            foreach ($request->carreras as $key => $value) {
                $dat.=$value.',';
            }
            $dat = trim($dat, ",");
            $where_carrera="usuario.carrera_id IN ($dat)";
        }

         if($request->periodos){
            $datx='';
            foreach ($request->periodos as $key => $periodo) {
                $datx.="'$periodo',";
            }
            $datx = trim($datx, ",");
            $where_periodo="usuario.periodo_academico IN ($datx)";
        }

         if($request->anios){
            $anios='';
            foreach ($request->anios as $key => $an) {
                $anios.=intval($an).',';
            }
            $anios = trim($anios, ",");
            $where_anios="usuario.anio_graduacion IN ($anios)";
        }      

        $request = request();
        $limit   = $request->input('length');
        $start   = $request->input('start');
        if (empty($request->input('search.value'))) {
            $registros = usuarioModel::Leftjoin('respuesta_encuesta', function($join) use($encuesta_id)
            {
                $join->on('respuesta_encuesta.usuario_id', '=', 'usuario.id')
                     ->where('respuesta_encuesta.encuesta_id',$encuesta_id);
            })->whereraw($where_carrera)
            ->whereraw($where_anios)
            ->whereraw($where_periodo)
            ->whereraw($where_respuesta)
            ->where('rol_id',3)
            ->orderBy('usuario.apellidos')
            ->skip($start)->take($limit)->get();
            
            $totalData     = usuarioModel::Leftjoin('respuesta_encuesta', function($join) use($encuesta_id)
            {
                $join->on('respuesta_encuesta.usuario_id', '=', 'usuario.id')
                     ->where('respuesta_encuesta.encuesta_id',$encuesta_id);
            })->whereraw($where_carrera)
            ->whereraw($where_anios)
            ->whereraw($where_periodo)
            ->whereraw($where_respuesta)
            ->where('rol_id',3)
            ->count();
            $totalFiltered = $totalData;
        } else {
            $search    = mb_strtoupper($request->input('search.value'));
            $registros = usuarioModel::Leftjoin('respuesta_encuesta', function($join) use($encuesta_id)
            {
                $join->on('respuesta_encuesta.usuario_id', '=', 'usuario.id')
                     ->where('respuesta_encuesta.encuesta_id',$encuesta_id);
            })
            ->where(function ($query) use ($search) {
                $query->where("nombres", 'ilike', '%' . $search . '%')
                    ->orWhere("apellidos", 'ilike', '%' . $search . '%')
                    ->orWhere("identificacion", 'ilike', '%' . $search . '%')
                    ->orWhere("email", 'ilike', '%' . $search . '%')
                    ->orWhere("periodo_academico", 'ilike', '%' . $search . '%')
                    ->orWhere("telefono", 'ilike', '%' . $search . '%');
            })->where('rol_id',3)
            ->whereraw($where_carrera)
            ->whereraw($where_anios)
            ->whereraw($where_periodo)
            ->whereraw($where_respuesta)
            ->orderBy('usuario.apellidos')
            ->skip($start)->take($limit)->get();
            $totalData     = usuarioModel::Leftjoin('respuesta_encuesta', function($join) use($encuesta_id)
            {
                $join->on('respuesta_encuesta.usuario_id', '=', 'usuario.id')
                     ->where('respuesta_encuesta.encuesta_id',$encuesta_id);
            })
            ->where(function ($query) use ($search) {
                $query->where("nombres", 'ilike', '%' . $search . '%')
                    ->orWhere("apellidos", 'ilike', '%' . $search . '%')
                    ->orWhere("identificacion", 'ilike', '%' . $search . '%')
                    ->orWhere("periodo_academico", 'ilike', '%' . $search . '%')
                    ->orWhere("email", 'ilike', '%' . $search . '%')
                    ->orWhere("telefono", 'ilike', '%' . $search . '%');
            })->where('rol_id',3)
            ->whereraw($where_carrera)
            ->whereraw($where_anios)
            ->whereraw($where_periodo)
            ->whereraw($where_respuesta)
            ->count();
            $totalFiltered = $totalData;
        }
        $data = array();



        if (!empty($registros)) {
            foreach ($registros as $key => $value) {
                //dd($value);
                $length   = strlen($value->id);

                //no han respondido
                $color='#DF4C10';
                $respuesta='NO';

                //en caso de que si ha respondido
                if($value->encuesta_id==$request->id){
                    $color='#B4DF10';
                    $respuesta='SI';
                }

                $usuario_data['identificacion'] = '<span>' . $value->identificacion . '</span>';
                $usuario_data['nombres']        = '<span>' . $value->apellidos . '<br> '.$value->nombres.'</span>';
                $usuario_data['email']          = '<span>' . $value->email . '</span>';
                $usuario_data['telefono']          = '<span>' . $value->telefono . '</span>';
                $usuario_data['respuesta']          = '<span class="dot" style=" background-color:  '.$color.' ;"></span><span> ' . $respuesta . '</span>';
                $usuario_data['telefono']       = '<span>' . $value->telefono . '</span>';                
                $usuario_data['periodo_academico']       = '<span>' . $value->periodo_academico . '</span>';
                $carrera=null;
                $usuario_data['carrera']       = '<span>' . $carrera . '</span>';
                $data[]= $usuario_data;                
            }
        }

        $json_data = [
            "draw"            => intval($request->input('draw')),
            "recordsTotal"    => intval($totalData),
            "recordsFiltered" => intval($totalFiltered),
            "data"            => $data,
        ];
        return json_encode($json_data);
    }
    public function responder_encuesta($codigo)
    {

        $id = decrypt($codigo);
       // dd($id);

        $encuesta = encuestaModel::find($id);
        if (is_null($encuesta)) {
            Session::flash('message-error', 'Usted esta ingresando a una url inválida');
            return Redirect::Back();
        }


     
            

resources/views/admin/encuestas/index.blade.php
<?php Autorizar(Request::path()); ?> 
@extends('layouts.master')
{{-- Page title --}}
@section('title')
    Encuesta del sistema @parent
@stop
{{-- page level styles --}}
@section('header_styles')
<!-- page vendors -->
<link href="{{ asset('assets/vendors/datatables/css/dataTables.bootstrap4.css')}}" rel="stylesheet">
    <link href="{{ asset('assets/vendors/datatables/css/buttons.bootstrap4.min.css')}}" rel="stylesheet">
        <link href="{{ asset('assets/css/responsive.dataTables.css')}}" rel="stylesheet">
            <link href="{{ asset('assets/css/pages/datatables.css')}}" rel="stylesheet">
                <!--end of page vendors -->
                <link href="{{asset('assets/plugins/jquery-colorbox/example1/colorbox.css')}}" rel="stylesheet"/>
                <link href="{{asset('assets/plugins/jsTree/style.css')}}" rel="stylesheet">
                    @stop
@section('content')
@include('alerts.errors')
@include('alerts.request')
@include('alerts.success')
                    <!-- Content Header (Page header) -->
                    <section class="content-header">
                        <h1>
                            Encuestas
                        </h1>
                    </section>
                    <!-- Main content -->
                    <section class="content">
                        <div class="row">
                                <div class="col-lg-12">
                                    <div class="card filterable">
                                        <div class="card-header clearfix">
                                            <h3 class="card-title pull-left m-t-6">
                                                <i class="ti-control-shuffle">
                                                </i>
                                                Gestión de Encuestas
                                            </h3>
                                            <div class="pull-right">
                                                <a class="btn btn-primary btn-sm" href="{{ url('subir_encuestas') }}">
                                                    Nueva
                                                </a>
                                            </div>
                                        </div>
                                        <div class="card-body">
                                            <div class="table-responsive">
                                                <table cellspacing="0" class="table" id="tables3" width="100%">
                                                    <thead>
                                                        <tr class="filters">
                                                            <th scope="col">
                                                                ID
                                                            </th>
                                                            <th scope="col">
                                                                NOMBRE
                                                            </th>
                                                            <th scope="col">
                                                                AÑOS DESPUES DE GRADUACIÓN A HABILITARSE
                                                            </th>
                                                            <th scope="col">
                                                                ACCIONES
                                                            </th>
                                                        </tr>
                                                    </thead>
                                                    <tbody>
                                                        @if (count($encuestas))
                                                         @foreach ($encuestas as $rol)
                                                        <tr id="tr{{ $rol->id }}">
                                                            <td>
                                                                {{ $rol->id }}
                                                            </td>
                                                            <td>
                                                                {{ $rol->nombre }}
                                                            </td>
                                                            <td align="right">
                                                                {{ $rol->anios }}
                                                            </td>
                                                            <td>
                                                                <a href="{{ route('encuestas.edit',$rol->id) }}">
                                                                    <i class="fa fa-fw fa-pencil text-primary actions_icon" title="Edit User">
                                                                    </i>
                                                                </a>
                                                                <a data-target="#delete" data-toggle="modal" href="#">
                                                                    <i class="fa fa-fw fa-times text-danger actions_icon" title="Delete User">
                                                                    </i>
                                                                </a>
                                                            </td>
                                                        </tr>
                                                        @endforeach
                                                    </tbody>
                                                </table>
                                                @endif
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
                        </div>
                    </section>
                    <!-- /.content -->
                    @stop
@section('footer_scripts')
                    <!--   page level js -->
                    <script src="{{ asset('assets/vendors/datatables/js/jquery.dataTables.js')}}" type="text/javascript">
                    </script>
                    <script src="{{ asset('assets/vendors/datatables/js/dataTables.bootstrap4.js')}}" type="text/javascript">
                    </script>
                    <script src="{{ asset('assets/vendors/datatables/js/dataTables.buttons.min.js')}}" type="text/javascript">
                    </script>
                    <script src="{{ asset('assets/vendors/datatables/js/buttons.print.min.js')}}" type="text/javascript">
                    </script>
                    <script src="{{ asset('assets/vendors/datatables/js/buttons.html5.min.js')}}" type="text/javascript">
                    </script>
                    <script src="{{ asset('assets/vendors/datatables/js/buttons.bootstrap4.min.js')}}" type="text/javascript">
                    </script>
                    <script src="{{ asset('assets/vendors/datatables/js/dataTables.responsive.js')}}" type="text/javascript">
                    </script>
                    <script src="{{ asset('assets/js/pages/advanced_tables.js')}}" type="text/javascript">
                    </script>
                    <!-- end of page level js -->
                    <script src="{{asset('assets/plugins/jquery-colorbox/jquery.colorbox.js')}}" type="text/javascript">
                    </script>
                    <script src="{{asset('assets/plugins/jsTree/jstree.min.js')}}">
                    </script>
                    <script type="text/javascript">
   



        'use strict';
  var table = $('#tables3').DataTable({
    language: {
        "decimal": "",
        "emptyTable": "No hay información",
        "info": "Mostrando _START_ a _END_ de _TOTAL_ Entradas",
        "infoEmpty": "Mostrando 0 to 0 of 0 Entradas",
        "infoFiltered": "(Filtrado de _MAX_ total entradas)",
        "infoPostFix": "",
        "thousands": ",",
        "lengthMenu": "Mostrar _MENU_ Entradas",
        "loadingRecords": "Cargando...",
        "processing": "Procesando...",
        "search": "Buscar:",
        "zeroRecords": "Sin resultados encontrados",
        "paginate": {
            "first": "Primero",
            "last": "Ultimo",
            "next": "Siguiente",
            "previous": "Anterior"
        }
    },
  
});


    $(document).ready(function(){
        $(".dataTables_length .form-control").removeClass('form-control-sm');
    })

    function administrar_permisos(id){
        var direccion="{{ url('configuracion/roles/administrar_permisos') }}/"+id;
        $.colorbox({href : direccion, width:"100%", height:"100%"});
    }
                    </script>
                    @stop

resources/views/admin/encuestas/subir_encuestas.blade.php
<?php Autorizar(Request::path()); ?> 
@extends('layouts.master')
@section('header_styles')
<link href="{{ asset('assets/vendors/sweetalert2/css/sweetalert2.min.css')}}" rel="stylesheet">
    <link href="{{asset('assets/selective/selectize.bootstrap3.css')}}" rel="stylesheet" type="text/css">
        <link href="{{ asset('assets/vendors/toastr/css/toastr.css') }}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/vendors/iCheck/css/all.css') }}" rel="stylesheet" type="text/css"/>
        <link href="{{ asset('assets/css/pages/toastr.css') }}" rel="stylesheet"/>
         <link rel="stylesheet" href="{{ asset('assets/vendors/select2/css/select2.min.css')}}">
        @endsection
@section('titulo','Crear usuario')
@section('content')
        <div class="breadcrumb">
            <h1>
                Subir Profesionales
            </h1>
        </div>
        <div class="separator-breadcrumb border-top">
        </div>
        <div class="row">
            <div class="col-md-12">
                <div class="card mb-4">
                    <div class="card-body">
                        <div class="card-title mb-3">
                            Nueva Encuesta
                        </div>
                        @include('alerts.errors')
                            @include('alerts.request')
                           {!! Form::open(['url'=>'subir_encuesta_post', 'method' => 'POST','files'=>'true']) !!}
                        <div class="row">
                            <div class="col-md-4 form-group mb-3">
                                <label for="nombre">
                                    Nombre de encuesta
                                </label>
                                {!! Form::Text('identificacion',null,['class'=>'form-control','placeholder'=>'Ingrese un nombre para la encuesta']) !!}
                            </div>
                            <div class="col-md-4 form-group mb-3">
                                <label for="nombre">
                                   Años despues de graduación para habilitar
                                </label>
                                {!! Form::Number('anios',null,['class'=>'form-control']) !!}
                            </div>
                            <div class="col-md-4 form-group mb-3">
                                @php
                                $periodos=App\usuarioModel::whereNotNull('periodo_academico')->distinct('periodo_academico')->pluck('periodo_academico','periodo_academico');
                                @endphp
                                     <label>Periodos Académico</label>
                                    {!!Form::select('periodos[]', $periodos,null, ['class' => 'select2','id'=>'periodos','multiple'])!!}
                            </div>
                            <div class="col-md-12 form-group mb-3">
                                <a href="graduados.xlsx">
                                    Descargar formato
                                </a>
                                <br>
                                    <label for="nombre">
                                        Excel de encuesta a subir
                                    </label>
                                    <input name="encuesta" type="file">
                                    </input>
                                </br>
                            </div>
                            <div class="col-md-12">
                                <button class="btn btn-primary" type="submit">
                                    Registrar
                                </button>
                            </div>
                        </div>
                        {!! Form::close() !!}
                    </div>
                </div>
            </div>
        </div>
        @endsection
@section('footer_scripts')
<script src="{{ asset('assets/vendors/sweetalert2/js/sweetalert2.min.js')}}" type="text/javascript"></script>
<script src="{{ asset('assets/vendors/toastr/js/toastr.min.js') }}"></script>
<script src="{{ asset('assets/vendors/iCheck/js/icheck.js') }}" type="text/javascript"></script>
<script src="{{ asset('assets/js/pages/ui-toastr.js') }}"></script>
<script src="{{asset('assets/vendors/select2/js/select2.js')}}" type="text/javascript"></script>
        <script type="text/javascript">
             $(".select2").select2({width: "100%"});
        </script>
        @endsection